//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_step_execution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batch_step_execution()
        {
            this.deviations = new HashSet<deviations>();
        }
    
        public int id { get; set; }
        public int batch_id { get; set; }
        public int step_id { get; set; }
        public int step_order { get; set; }
        public string step_name { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string status { get; set; }
        public Nullable<decimal> actual_temp_c { get; set; }
        public Nullable<decimal> actual_pressure_bar { get; set; }
        public Nullable<int> actual_duration_min { get; set; }
        public string operator_comment { get; set; }
        public Nullable<int> started_by { get; set; }
        public Nullable<int> completed_by { get; set; }
        public Nullable<bool> deviation_flag { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual production_batches production_batches { get; set; }
        public virtual technology_steps technology_steps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deviations> deviations { get; set; }
    }
}
