//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_raw_material_usage
    {
        public int id { get; set; }
        public int batch_id { get; set; }
        public int raw_material_batch_id { get; set; }
        public decimal used_quantity_kg { get; set; }
        public Nullable<System.DateTime> used_at { get; set; }
    
        public virtual production_batches production_batches { get; set; }
        public virtual raw_material_batches raw_material_batches { get; set; }
    }
}
