//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviations
    {
        public int id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> step_execution_id { get; set; }
        public string deviation_type { get; set; }
        public string parameter_name { get; set; }
        public string planned_value { get; set; }
        public string actual_value { get; set; }
        public string severity { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public string resolution { get; set; }
        public Nullable<System.DateTime> detected_at { get; set; }
        public Nullable<System.DateTime> resolved_at { get; set; }
        public Nullable<int> detected_by { get; set; }
        public Nullable<int> resolved_by { get; set; }
    
        public virtual batch_step_execution batch_step_execution { get; set; }
        public virtual production_batches production_batches { get; set; }
    }
}
