//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string equipment_type { get; set; }
        public string location { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> last_calibration { get; set; }
        public Nullable<System.DateTime> next_calibration { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public string description { get; set; }
    }
}
