//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        public int id { get; set; }
        public string event_type { get; set; }
        public string source_type { get; set; }
        public Nullable<int> source_id { get; set; }
        public string message { get; set; }
        public string severity { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<bool> is_read { get; set; }
    }
}
