//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratory_tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public laboratory_tests()
        {
            this.test_parameters = new HashSet<test_parameters>();
        }
    
        public int id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> raw_material_batch_id { get; set; }
        public string test_type { get; set; }
        public string test_number { get; set; }
        public System.DateTime analysis_date { get; set; }
        public int analyst_id { get; set; }
        public string status { get; set; }
        public string priority { get; set; }
        public string decision { get; set; }
        public string decision_comment { get; set; }
        public Nullable<System.DateTime> decision_date { get; set; }
        public Nullable<int> decided_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual production_batches production_batches { get; set; }
        public virtual raw_material_batches raw_material_batches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_parameters> test_parameters { get; set; }
    }
}
