//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class terEntities : DbContext
    {
        public terEntities()
            : base("name=terEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch_raw_material_usage> batch_raw_material_usage { get; set; }
        public virtual DbSet<batch_step_execution> batch_step_execution { get; set; }
        public virtual DbSet<deviations> deviations { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<laboratory_tests> laboratory_tests { get; set; }
        public virtual DbSet<production_batches> production_batches { get; set; }
        public virtual DbSet<production_orders> production_orders { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<raw_material_batches> raw_material_batches { get; set; }
        public virtual DbSet<raw_materials> raw_materials { get; set; }
        public virtual DbSet<recipe_components> recipe_components { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
        public virtual DbSet<status_history> status_history { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<technology_map> technology_map { get; set; }
        public virtual DbSet<technology_steps> technology_steps { get; set; }
        public virtual DbSet<test_parameters> test_parameters { get; set; }
        public virtual DbSet<user_actions> user_actions { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
