//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public production_orders()
        {
            this.production_batches = new HashSet<production_batches>();
        }
    
        public int id { get; set; }
        public string order_number { get; set; }
        public int product_id { get; set; }
        public int recipe_id { get; set; }
        public int technology_map_id { get; set; }
        public decimal planned_quantity_kg { get; set; }
        public string status { get; set; }
        public Nullable<int> priority { get; set; }
        public System.DateTime planned_start_date { get; set; }
        public Nullable<System.DateTime> planned_end_date { get; set; }
        public Nullable<System.DateTime> actual_start_date { get; set; }
        public Nullable<System.DateTime> actual_end_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_batches> production_batches { get; set; }
        public virtual products products { get; set; }
        public virtual recipes recipes { get; set; }
        public virtual technology_map technology_map { get; set; }
    }
}
