//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_batches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public production_batches()
        {
            this.batch_raw_material_usage = new HashSet<batch_raw_material_usage>();
            this.batch_step_execution = new HashSet<batch_step_execution>();
            this.deviations = new HashSet<deviations>();
            this.laboratory_tests = new HashSet<laboratory_tests>();
        }
    
        public int id { get; set; }
        public string batch_number { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public int recipe_id { get; set; }
        public int technology_map_id { get; set; }
        public decimal planned_quantity_kg { get; set; }
        public Nullable<decimal> actual_quantity_kg { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string extruder_program { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> started_by { get; set; }
        public Nullable<int> completed_by { get; set; }
        public string quality_decision { get; set; }
        public string quality_comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_raw_material_usage> batch_raw_material_usage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_step_execution> batch_step_execution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deviations> deviations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<laboratory_tests> laboratory_tests { get; set; }
        public virtual production_orders production_orders { get; set; }
        public virtual products products { get; set; }
        public virtual recipes recipes { get; set; }
        public virtual technology_map technology_map { get; set; }
    }
}
