//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class raw_material_batches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public raw_material_batches()
        {
            this.batch_raw_material_usage = new HashSet<batch_raw_material_usage>();
            this.laboratory_tests = new HashSet<laboratory_tests>();
        }
    
        public int id { get; set; }
        public int raw_material_id { get; set; }
        public string batch_number { get; set; }
        public string supplier_batch_number { get; set; }
        public decimal quantity { get; set; }
        public string unit { get; set; }
        public System.DateTime receipt_date { get; set; }
        public string supplier { get; set; }
        public string laboratory_status { get; set; }
        public string status { get; set; }
        public string storage_location { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_raw_material_usage> batch_raw_material_usage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<laboratory_tests> laboratory_tests { get; set; }
        public virtual raw_materials raw_materials { get; set; }
    }
}
