//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_components
    {
        public int id { get; set; }
        public int recipe_id { get; set; }
        public int raw_material_id { get; set; }
        public decimal percentage { get; set; }
        public int load_order { get; set; }
        public Nullable<decimal> tolerance_min { get; set; }
        public Nullable<decimal> tolerance_max { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual raw_materials raw_materials { get; set; }
        public virtual recipes recipes { get; set; }
    }
}
