//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_history
    {
        public int id { get; set; }
        public string entity_type { get; set; }
        public int entity_id { get; set; }
        public string old_status { get; set; }
        public string new_status { get; set; }
        public Nullable<System.DateTime> changed_at { get; set; }
        public Nullable<int> changed_by { get; set; }
        public string comment { get; set; }
    }
}
