//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class technology_steps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public technology_steps()
        {
            this.batch_step_execution = new HashSet<batch_step_execution>();
        }
    
        public int id { get; set; }
        public int technology_map_id { get; set; }
        public int step_order { get; set; }
        public string step_name { get; set; }
        public string step_type { get; set; }
        public Nullable<decimal> planned_temp_c { get; set; }
        public Nullable<int> planned_duration_min { get; set; }
        public Nullable<decimal> planned_pressure_bar { get; set; }
        public Nullable<decimal> tolerance_temp_c { get; set; }
        public Nullable<int> tolerance_duration_min { get; set; }
        public Nullable<decimal> tolerance_pressure_bar { get; set; }
        public Nullable<bool> is_mandatory { get; set; }
        public string instruction { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_step_execution> batch_step_execution { get; set; }
        public virtual technology_map technology_map { get; set; }
    }
}
