//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_parameters
    {
        public int id { get; set; }
        public int test_id { get; set; }
        public string parameter_name { get; set; }
        public Nullable<decimal> measured_value { get; set; }
        public Nullable<decimal> standard_value_min { get; set; }
        public Nullable<decimal> standard_value_max { get; set; }
        public string unit { get; set; }
        public string result { get; set; }
        public string analyst_comment { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual laboratory_tests laboratory_tests { get; set; }
    }
}
