//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_actions
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string action_type { get; set; }
        public string entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public string details { get; set; }
        public string ip_address { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
